version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python -m pip install --upgrade pip
      - run: pip install -r GitHubApi567-hw4a/requirements.txt
      - run: |
          cd GitHubApi567-hw4a
          pytest -q
workflows:
  build_and_test:
    jobs:
      - build
