version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: python -m pip install --upgrade pip
      - run:
          name: Install deps
          command: pip install -r GitHubApi567-hw4a/requirements.txt
      - run:
          name: Run tests
          command: |
            cd GitHubApi567-hw4a
            pytest -q
workflows:
  build_and_test:
    jobs:
      - build
